// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Extension.44e1869c-e986-4044-a159-586ca334e043";
        public const string Name = "Extension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simon Sørensen";
        public const string Tags = "";
    }
}
