// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TTSE
{
    internal sealed partial class Vsix
    {
        public const string Id = "TTSE.4f420198-4764-4063-8007-fac4d84e411c";
        public const string Name = "TTSE";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simon Sørensen";
        public const string Tags = "";
    }
}
