// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExceptionHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExceptionHelper.552567a9-d066-401e-b45c-d62da7d7b8f2";
        public const string Name = "ExceptionHelper";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simon Sørensen";
        public const string Tags = "";
    }
}
