// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSCodingBuddy
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSCodingBuddy.552567a9-d066-401e-b45c-d62da7d7b8f2";
        public const string Name = "VSCodingBuddy";
        public const string Description = @"Helpful AI error message bot ai ai chatgpt-3";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simon Sørensen";
        public const string Tags = "";
    }
}
